# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quakedbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date Published')),
                ('magnitude', models.FloatField(default=0.0)),
                ('remarks', models.CharField(help_text='tsunami alert', max_length=200, verbose_name='Remarks ')),
                ('epicentre', models.CharField(max_length=200, verbose_name='Epicentre ')),
            ],
        ),
    ]
